name: formularios_front
description: "A Flutter Clean Architecture project for Intelicity demands."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  auto_injector: ^2.0.4
  go_router: ^13.2.3
  dartz: ^0.10.1
  google_fonts: ^6.2.1
  uno: ^1.1.9
  intl: ^0.18.1
  logger: ^2.2.0
  provider: ^6.1.2
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
flutter_intl:
  enabled: true